<div class="alert alert-block alert-success">

Print the first 200 characters. </div>


In [112]:
# Open the file and read its contents
with open("Harry_porter.txt", "r", encoding="utf-8") as f:
    raw_text = f.read()

# Print the total number of characters
print("Total number of characters:", len(raw_text))

# Print the first 200 characters
print(raw_text[:200])


Total number of characters: 20042
When Mr. and Mrs. Dursley woke up on the dull, gray Tuesday our story
starts, there was nothing about the cloudy sky outside to suggest that strange
and mysterious things would soon be happening all o


<div class="alert alert-block alert-success">

Uisng re.split for the character splitting. </div>


In [113]:
import re

text = "Hello, everyone. We, are still testing."
result = re.split(r'(\s)', text)

print(result)

['Hello,', ' ', 'everyone.', ' ', 'We,', ' ', 'are', ' ', 'still', ' ', 'testing.']


<div class="alert alert-block alert-success">

Modify the splitting so sepcial characters can be split too </div>

In [114]:
result = re.split(r'([,.]|\s)', text)

print(result)

['Hello', ',', '', ' ', 'everyone', '.', '', ' ', 'We', ',', '', ' ', 'are', ' ', 'still', ' ', 'testing', '.', '']


<div class="alert alert-block alert-success">

Removing reductant white space characters iin the splitting </div>

In [115]:
result = [item for item in result if item.strip()]
print(result)

['Hello', ',', 'everyone', '.', 'We', ',', 'are', 'still', 'testing', '.']


<div class="alert alert-block alert-success">

Tokenization with special characters and removing white spaces for better tokenization</div>

In [116]:
text = "Hello, world. Is this-- a test?"
result = re.split(r'([,.:;?_!"()\']|--|\s)', text)
result = [item.strip() for item in result if item.strip()]
print(result)

['Hello', ',', 'world', '.', 'Is', 'this', '--', 'a', 'test', '?']


<div class="alert alert-block alert-success">

Applying the tokenization to the harry portext book</div>

In [117]:
preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', raw_text)
preprocessed = [item.strip() for item in preprocessed if item.strip()]
print(preprocessed[:100])

['When', 'Mr', '.', 'and', 'Mrs', '.', 'Dursley', 'woke', 'up', 'on', 'the', 'dull', ',', 'gray', 'Tuesday', 'our', 'story', 'starts', ',', 'there', 'was', 'nothing', 'about', 'the', 'cloudy', 'sky', 'outside', 'to', 'suggest', 'that', 'strange', 'and', 'mysterious', 'things', 'would', 'soon', 'be', 'happening', 'all', 'over', 'the', 'country', '.', 'Mr', '.', 'Dursley', 'hummed', 'as', 'he', 'picked', 'out', 'his', 'most', 'boring', 'tie', 'for', 'work', ',', 'and', 'Mrs', '.', 'Dursley', 'gossiped', 'away', 'happily', 'as', 'she', 'wrestled', 'a', 'screaming', 'Dudley', 'into', 'his', 'high', 'chair', '.', 'None', 'of', 'them', 'noticed', 'a', 'large', ',', 'tawny', 'owl', 'flutter', 'past', 'the', 'window', '.', 'At', 'half', 'past', 'eight', ',', 'Mr', '.', 'Dursley', 'picked', 'up']


In [118]:
print(len(preprocessed))

4307


In [119]:
all_words = sorted(set(preprocessed))
vocab_size = len(all_words)

print(vocab_size)

1093


<div class="alert alert-block alert-success">

Vocabulary token: Involves ranking the text alphabetically and sorted with number attached to them</div>

In [120]:
vocab = {token:integer for integer,token in enumerate(all_words)}
for i, item in enumerate(vocab.items()):
    print(item)
    if i >= 20:
        break

('!', 0)
('(', 1)
(')', 2)
(',', 3)
('.', 4)
(':', 5)
(';', 6)
('?', 7)
('A', 8)
('About', 9)
('After', 10)
('Albus', 11)
('All', 12)
('Although', 13)
('And', 14)
('As', 15)
('At', 16)
('Bonfire', 17)
('Britain', 18)
('But', 19)
('Can’t', 20)


<div class="alert alert-block alert-info">
    
--Encode and Decode    

Step 1: Store the vocabulary as a class attribute for access in the encode and decode methods
    
Step 2: Create an inverse vocabulary that maps token IDs back to the original text tokens

Step 3: Process input text into token IDs

Step 4: Convert token IDs back into text

Step 5: Replace spaces before the specified punctuation

</div>



In [121]:
class SimpleTokenizerV1:
    def __init__(self, vocab):
        self.str_to_int = vocab
        self.int_to_str = {i:s for s,i in vocab.items()}
    
    def encode(self, text):
        preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', text)
                                
        preprocessed = [
            item.strip() for item in preprocessed if item.strip()
        ]
        ids = [self.str_to_int[s] for s in preprocessed]
        return ids
        
    def decode(self, ids):
        text = " ".join([self.int_to_str[i] for i in ids])
        # Replace spaces before the specified punctuations
        text = re.sub(r'\s+([,.?!"()\'])', r'\1', text)
        return text

<div class="alert alert-block alert-success">

Trying out an example of the deocde and decode</div>

In [122]:
tokenizer = SimpleTokenizerV1(vocab)

text = "What you say?"
ids = tokenizer.encode(text)
print(ids)

[119, 1028, 745, 7]


In [123]:
tokenizer.decode(ids)

'What you say?'

<div class="alert alert-block alert-success">

If any character is in the example and not in the trianing it will show error</div>

In [124]:
#Messi is not in the Harry_porter text
text = "Messi do you like tea?" 
print(tokenizer.encode(text))

KeyError: 'Messi'

<div class="alert alert-block alert-warning">

In the previous example Messi is not in the training text. So to solve that we
are going to use another decode method. To solve that we can use a new token to accomodate
for unknown text which is <|unk|> and also to seperate between two different text we
are going to use <|endoftext|>
</div>



In [125]:
all_tokens = sorted(list(set(preprocessed)))
all_tokens.extend(["<|endoftext|>", "<|unk|>"])

vocab = {token:integer for integer,token in enumerate(all_tokens)}

len(vocab.items())

1095

In [126]:
#To see the changes of the two new encoding
for i, item in enumerate(list(vocab.items())[-10:]):
    print(item)

('“You', 1085)
('“You’d', 1086)
('“but', 1087)
('“everyone”', 1088)
('“is', 1089)
('“—', 1090)
('”', 1091)
('”A', 1092)
('<|endoftext|>', 1093)
('<|unk|>', 1094)


In [127]:
class SimpleTokenizerV2:
    def __init__(self, vocab):
        self.str_to_int = vocab
        self.int_to_str = { i:s for s,i in vocab.items()}
    
    def encode(self, text):
        preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', text)
        preprocessed = [item.strip() for item in preprocessed if item.strip()]
        preprocessed = [
            item if item in self.str_to_int 
            else "<|unk|>" for item in preprocessed
        ]

        ids = [self.str_to_int[s] for s in preprocessed]
        return ids
        
    def decode(self, ids):
        text = " ".join([self.int_to_str[i] for i in ids])
        # Replace spaces before the specified punctuations
        text = re.sub(r'\s+([,.:;?!"()\'])', r'\1', text)
        return text

In [128]:
tokenizer = SimpleTokenizerV2(vocab)

text1 = "Messi do you like tea?"
text2 = "You sure it is raining."

text = " <|endoftext|> ".join((text1, text2))

print(text)

Messi do you like tea? <|endoftext|> You sure it is raining.


In [129]:
decode = tokenizer.encode(text)
print(decode)

[1094, 316, 1028, 545, 881, 7, 1093, 124, 862, 504, 502, 1094, 4]


In [130]:
encode = tokenizer.decode(decode)
print(encode)

<|unk|> do you like tea? <|endoftext|> You sure it is <|unk|>.


<div class="alert alert-block alert-warning">

We also have some other options like:
[BOS] (beginning of sequence)
[EOS] (end of sequence):
[PAD] (padding): When training LLMs with batch sizes larger than one,
the batch might contain texts of varying lengths.

</div>


<div class="alert alert-block alert-warning">

GPT models doesn't use an <|unk|> token but used byte pair encoding tokenizer, which breaks
down words into subword units and more easier to decode and decode and get semantic 
meaning of the text
</div>

**Byte Pair Encoding Tokenization**

In [131]:
#using tiktoken from openai
import importlib
import tiktoken


In [132]:
tokenizer = tiktoken.get_encoding("gpt2")

In [133]:
text = (
    "Messi do you like tea?." "You sure it is raining."
     "What you say?"
)

encode = tokenizer.encode(text)

print(encode)

[36479, 72, 466, 345, 588, 8887, 30, 13, 1639, 1654, 340, 318, 43079, 13, 2061, 345, 910, 30]


In [134]:
decode = tokenizer.decode(integers)

print(decode)

Messi do you like tea?.You sure it is raining.What you say?


In [135]:
#encoding the harry_porter text
with open("Harry_porter.txt", "r", encoding="utf-8") as f:
    raw_text = f.read()

encode = tokenizer.encode(raw_text)
print(len(encode))

5668


<div class="alert alert-block alert-warning">

Slidding window in LLM. Shifting the output by 1. Like input is
    a, b, c, d abd output is b, c, d, e
</div>

In [136]:
context_size = 4

x = encode[:context_size]
y = encode[1:context_size+1]

print(f"x: {x}")
print(f"y:      {y}")

x: [2215, 1770, 13, 290]
y:      [1770, 13, 290, 9074]


In [137]:
for i in range(1, context_size+1):
    context = encode[:i]
    desired = encode[i]

    print(context, "---->", desired)

[2215] ----> 1770
[2215, 1770] ----> 13
[2215, 1770, 13] ----> 290
[2215, 1770, 13, 290] ----> 9074


In [138]:
for i in range(1, context_size+1):
    context = encode[:i]
    desired = encode[i]

    print(tokenizer.decode(context), "---->", tokenizer.decode([desired]))

When ---->  Mr
When Mr ----> .
When Mr. ---->  and
When Mr. and ---->  Mrs


**IMPLEMENTING A DATA LOADER**

In [139]:
from torch.utils.data import Dataset, DataLoader

In [140]:
class GPTDatasetV1(Dataset):
    def __init__(self, txt, tokenizer, max_length, stride):
        self.input_ids = []
        self.target_ids = []

        # Tokenize the entire text
        token_ids = tokenizer.encode(txt, allowed_special={"<|endoftext|>"})

        # Use a sliding window to chunk the book into overlapping sequences of max_length
        for i in range(0, len(token_ids) - max_length, stride):
            input_chunk = token_ids[i:i + max_length]
            target_chunk = token_ids[i + 1: i + max_length + 1]
            self.input_ids.append(torch.tensor(input_chunk))
            self.target_ids.append(torch.tensor(target_chunk))

    def __len__(self):
        return len(self.input_ids)

    def __getitem__(self, idx):
        return self.input_ids[idx], self.target_ids[idx]

In [141]:
def create_dataloader_v1(txt, batch_size=4, max_length=256, 
                         stride=128, shuffle=True, drop_last=True,
                         num_workers=0):

    # Initialize the tokenizer
    tokenizer = tiktoken.get_encoding("gpt2")

    # Create dataset
    dataset = GPTDatasetV1(txt, tokenizer, max_length, stride)

    # Create dataloader
    dataloader = DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        drop_last=drop_last,
        num_workers=num_workers
    )

    return dataloader

<div class="alert alert-block alert-warning">
    
#recall on how context, stride and sliding window works.

Context: How many elements are included in the window at one time (length of the input).

Stride: The size of the jump when sliding the window forward (controls overlap).

Sliding Window: The process of moving the window across the sequence to extract data step-by-step. 

Say words is a,b,c,d, e, f, g, h,i.

Lets say context = 3, sliding window is 1, stride is 2

0:
Input: a, b, c. ouput: b,c,d

1:
Input: c,d,e outpu: d,e,f
</div>

In [142]:
with open("Harry_porter.txt", "r", encoding="utf-8") as f:
    raw_text = f.read()

In [143]:
import torch
print("PyTorch version:", torch.__version__)
dataloader = create_dataloader_v1(
    raw_text, batch_size=1, max_length=4, stride=2, shuffle=False
)

data_iter = iter(dataloader)
first_batch = next(data_iter)
print(first_batch)

PyTorch version: 2.4.1
[tensor([[2215, 1770,   13,  290]]), tensor([[1770,   13,  290, 9074]])]


In [144]:
second_batch = next(data_iter)
print(second_batch)

[tensor([[  13,  290, 9074,   13]]), tensor([[ 290, 9074,   13,  360]])]


In [145]:
third_batch = next(data_iter)
print(third_batch)

[tensor([[9074,   13,  360, 1834]]), tensor([[  13,  360, 1834, 1636]])]


In [146]:
dataloader = create_dataloader_v1(raw_text, batch_size=8, max_length=4, stride=4, shuffle=False)

data_iter = iter(dataloader)
inputs, targets = next(data_iter)
print("Inputs:\n", inputs)
print("\nTargets:\n", targets)

Inputs:
 tensor([[ 2215,  1770,    13,   290],
        [ 9074,    13,   360,  1834],
        [ 1636, 19092,   510,   319],
        [  262, 19222,    11, 12768],
        [ 3431,   674,  1621,   198],
        [  301,  5889,    11,   612],
        [  373,  2147,   546,   262],
        [40026,  6766,  2354,   284]])

Targets:
 tensor([[ 1770,    13,   290,  9074],
        [   13,   360,  1834,  1636],
        [19092,   510,   319,   262],
        [19222,    11, 12768,  3431],
        [  674,  1621,   198,   301],
        [ 5889,    11,   612,   373],
        [ 2147,   546,   262, 40026],
        [ 6766,  2354,   284,  1950]])


**CREATE TOKEN EMBEDDINGS**

In [147]:
input_ids = torch.tensor([2, 3, 5, 1])


In [148]:
vocab_size = 6
output_dim = 3

torch.manual_seed(42)
embedding_layer = torch.nn.Embedding(vocab_size, output_dim,max_norm=1.0)

In [149]:
print(embedding_layer.weight)

Parameter containing:
tensor([[ 1.9269,  1.4873, -0.4974],
        [ 0.4396, -0.7581,  1.0783],
        [ 0.8008,  1.6806,  0.3559],
        [-0.6866,  0.6105,  1.3347],
        [-0.2316,  0.0418, -0.2516],
        [ 0.8599, -0.3097, -0.3957]], requires_grad=True)


In [150]:
print(embedding_layer(torch.tensor([0])))

tensor([[ 0.7756,  0.5986, -0.2002]], grad_fn=<EmbeddingBackward0>)


In [151]:
print(embedding_layer(input_ids))

tensor([[ 0.4225,  0.8867,  0.1878],
        [-0.4237,  0.3767,  0.8237],
        [ 0.8599, -0.3097, -0.3957],
        [ 0.3164, -0.5456,  0.7760]], grad_fn=<EmbeddingBackward0>)


<div class="alert alert-block alert-warning">

Positional encoding.
Apart from encoding we also need to do positional encoding to get proper meaning of the
sentence. The positional encoding can be absolute encoding (considering only particular word) or relative encoding (considering the word relative to other words) as used in chatgpt
</div>

In [152]:
vocab_size = 50257
output_dim = 256

token_embedding_layer = torch.nn.Embedding(vocab_size, output_dim)

In [153]:
dataloader = create_dataloader_v1(
    raw_text, batch_size=8, max_length=4,
    stride=4, shuffle=False
)
data_iter = iter(dataloader)
inputs, targets = next(data_iter)

In [154]:
print("Token IDs:\n", inputs)
print("\nInputs shape:\n", inputs.shape)

Token IDs:
 tensor([[ 2215,  1770,    13,   290],
        [ 9074,    13,   360,  1834],
        [ 1636, 19092,   510,   319],
        [  262, 19222,    11, 12768],
        [ 3431,   674,  1621,   198],
        [  301,  5889,    11,   612],
        [  373,  2147,   546,   262],
        [40026,  6766,  2354,   284]])

Inputs shape:
 torch.Size([8, 4])


In [155]:
token_embeddings = token_embedding_layer(inputs)
print(token_embeddings.shape)

torch.Size([8, 4, 256])


In [156]:
context_length = max_length
pos_embedding_layer = torch.nn.Embedding(context_length, output_dim)

In [157]:
pos_embeddings = pos_embedding_layer(torch.arange(max_length))
print(pos_embeddings.shape)

torch.Size([4, 256])


In [158]:
input_embeddings = token_embeddings + pos_embeddings
print(input_embeddings.shape)

torch.Size([8, 4, 256])
